### ISSUE TITLE
Fatal error during compilation

### ISSUE THREAD

**Issue by jpalmer1026** [grails-plugins/grails-rest-client-builder#30]
I'm having difficulties installing the plugin. I'm using Grails 2.2.3 and the exception I'm getting is:

`Fatal error during compilation org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/Users/jeff/.grails/ivy-cache/org.grails/grails-hibernate/jars/grails-hibernate-2.2.3.jar!/org/codehaus/groovy/grails/compiler/gorm/GormTransformer.class]; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/type/classreading/AnnotationMetadataReadingVisitor`

**Comment by wureka** [comment]
Why not try Grails 2.4?
This plugin works in Grails 2.4.x
